name: Edge AI autoencoder 
slug: edge_ai_gateway_auto
version: "1.0.5"
description: Edge AI autoencoder
arch:
  - aarch64

startup: services
boot: auto
host_network: true
map:
  - share:rw
options: {}
schema: {}